enum AuditEventType {
  transactionCreated,
  debtCreated,
  debtUpdated,
  debtRepaid,
  debtSettled,
  debtClosed,
  debtReopened,
  transferExecuted,
  walletCreated,
  walletRenamed,
  walletArchived,
  contactCreated,
  attachmentCreated,
}
